org.slf4j.simpleLogger.defaultLogLevel=error
org.slf4j.simpleLogger.log.reactor.core.Exceptions=off
org.slf4j.simpleLogger.log.reactor.netty.channel.ChannelOperationsHandler=off
org.slf4j.simpleLogger.log.io.netty.channel.AbstractChannelHandlerContext=warn
org.slf4j.simpleLogger.log.io.netty.resolver.dns.DnsServerAddressStreamProviders=off
